// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kvzemkqmxtqsvbmmqngq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt2emVta3FteHRxc3ZibW1xbmdxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1OTU2MzQsImV4cCI6MjA3MDE3MTYzNH0.6wAi0daYyyXQR43KZBzH2dnY7IG_dKSuftioclrqWFE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});